name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Node.js
        run: npm install
        working-directory: server
      - name: Run tests on Node.js
        run: npm test
        working-directory: server
      - name: Install dependencies for Vue.js
        run: npm install
        working-directory: client
      - name: Run prettier for Vue.js
        run: npm run prettier
        working-directory: client
      - name: Run ES Lint for Vue.js
        run: npm run lint
        working-directory: client
