
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      - name: Install dependencies on Node.js
        run: npm install
        working-directory: server
      - name: Run tests on Node.js
        run: npm run test
        working-directory: server
