name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for Node.js
        run: npm install
        working-directory: server
      - name: Run tests on Node.js
        run: npm test
        working-directory: server
      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          eslint_dir: server/
          prettier_dir: server/
          github_token: ${{ secrets.github_token }}
          eslint: true
          prettier: true
          auto_fix: true
          git_email: letra.extension@gmail.com

